% clear;
fprintf('Modularity\n\n');
% input = load('synthetic_data.mat');
% struct "input" will be generated by the "data_generator.m" file
% or it can be loaded from the disk(i.e previously saved synthetic data)
% input = load('synthetic_data_8192_5_128.mat');

load('synth_final_used.mat');
dataset_name = 'Synthetic';
A = input.data;
N = input.N;
d = input.d;
K = input.K; %Number of Groups

%----------------------------

% dataset_name = 'Jammu';
% A = csvread('../Dataset/jammu_data_preprocessed_1.csv');
% A = A(1:1024, :);
% N = size(A,1);
% d = size(A,2);
% K = 2^5;

tic
global lambda;
global  grp_cell;
global index;
global distanceMat;


% lamb = [1,5,10,15,20,25,30,35,40,45];
% lamb = [10,20,30,40,50,60];
% lamb = [10,30,50,70,90,110];
% lamb = [7,14,21,28,35,42,49,56];
lamb = [6,12,18,24,30,36,42,48];
% lamb = [8,16,24,32,40,48,56];
l = length(lamb);

diver_met_vect = zeros(l,1);
variance_met_vect = zeros(l,1);
var_of_grp_var_met_vect = zeros(l,1);
var_of_grp_mean_met_vect = zeros(l,1);

grp_cell = cell(K,1);
distanceMat = squareform(pdist(A));

k=1;
reps = 10;

diver_box = zeros(reps, l);
variance_box = zeros(reps, l);
var_of_grp_var_box = zeros(reps, l);
var_of_grp_mean_box = zeros(reps, l);


for lambda=lamb
    
    for r=1:reps
        
        fprintf('Modularity\n\n\n');
        
        index=1;  %Global Variable
        
        fprintf('lambda: %d\n', lambda);

        rec_modularity(K, 1:N, N);

        fprintf('1st Metric: Students Distribution\n');
        grp_size = zeros(K,1);

        for i=1:K
            grp_size(i) = length(grp_cell{i});
        end

        %----make groups uniform
        [grp_cell, grp_size] = make_group_uniform(grp_cell, N, K, grp_size);
        %----
    
        temp1 = var(grp_size);
        variance_met_vect(k)=temp1;
        variance_box(r,k) = temp1;
        fprintf('Variance = %f\n\n', temp1);
        
        [M3, M4] = M3_M4(grp_cell, K, d, A);
        
        fprintf('Diversity(M4)\n');

        temp1 = M4;      

        diver_met_vect(k) = temp1;
        diver_box(r, k) = temp1;
        fprintf('Diversity Result(M4) = %f\n\n', temp1);

        fprintf('Var of group var(M3)\n');

        temp1 = M3;
        var_of_grp_var_met_vect(k) = temp1;
        var_of_grp_var_box(r, k) = temp1;
        
        fprintf('Var of group var(M3) = %f\n\n', temp1);
        
        
        fprintf('Var of group means(M2)\n');
        temp1 = M2_variance_of_grp_means(grp_cell, K, d, A);
        var_of_grp_mean_met_vect(k) = temp1;
        var_of_grp_mean_box(r, k) = temp1;
        fprintf('Var of group means(M2) = %f\n\n', temp1);
        
        toc
            
    end
    
    k = k+1;

end

[~, final_lambda_ind] = max(mean(diver_box));
% [~, final_lambda_ind] = min(mean(var_of_grp_var_box));
% [~, final_lambda_ind] = min(mean(var_of_grp_mean_box));
final_lambda = lamb(final_lambda_ind);


dirName = datestr(now, 'HH:MM:SS.FFF');
mkdir(strcat(dataset_name, '/',dirName));


% figure
% boxplot(variance_box, lamb)
% hold on
% plot(1:l, mean(variance_box), '-ob', 'LineWidth', 2.3)
% xlabel('\textbf{lambda}$(\lambda) \rightarrow$', 'Interpreter', 'latex', 'FontSize', 16)
% ylabel('\textbf{Variation of Group Size (VGS)} $\rightarrow$', 'Interpreter', 'latex', 'FontSize', 14)
% set(gca,'FontSize',13)
% print(strcat(dataset_name,'/',dirName, '/VGS'), '-dpng');
% close

figure
boxplot(diver_box, lamb)
hold on
plot(1:l, mean(diver_box), '-or', 'LineWidth', 2.3)
% title('Diversity')
% legend('Diversity')
xlabel('\textbf{lambda}$(\lambda) \rightarrow$', 'Interpreter', 'latex', 'FontSize', 16)
ylabel('\textbf{Total Group Diversity (TGD)} $\rightarrow$', 'Interpreter', 'latex', 'FontSize', 14)
set(gca,'FontSize',13)
print(strcat(dataset_name,'/',dirName, '/TGD'), '-dpng');
close


figure
boxplot(var_of_grp_var_box, lamb)
hold on
plot(1:l, mean(var_of_grp_var_box), '-ok', 'LineWidth', 2.3)
% title('Uniformity')
xlabel('\textbf{lambda}$(\lambda) \rightarrow$', 'Interpreter', 'latex', 'FontSize', 16)
ylabel('\textbf{Variation of Group Variance (VGV)} $\rightarrow$', 'Interpreter', 'latex', 'FontSize', 12)
set(gca,'FontSize',13)
print(strcat(dataset_name,'/',dirName, '/VGV'), '-dpng');
close


figure
boxplot(var_of_grp_mean_box, lamb)
hold on
plot(1:l, mean(var_of_grp_mean_box), '-ok', 'LineWidth', 2.3)
% title('Uniformity')
xlabel('\textbf{lambda}$(\lambda) \rightarrow$', 'Interpreter', 'latex', 'FontSize', 16)
ylabel('\textbf{Variation of Group Means (VGM)} $\rightarrow$', 'Interpreter', 'latex', 'FontSize', 12)
set(gca,'FontSize',13)
print(strcat(dataset_name,'/',dirName, '/VGM'), '-dpng');
close



%% -------------------------------Uniform Kmeans--------------------------------------------

U_diver_box = zeros(reps, 1);
U_variance_box = zeros(reps, 1);
U_var_of_grp_var_box = zeros(reps, 1);
U_var_of_grp_mean_box = zeros(reps, 1);

for r=1:reps
       
    tic
    fprintf('\n\n Uniform Kmeans\n\n');
    Kmns = floor(N/K);
    [U_grp_cell, U_grp_size] = uniform_kmeans(A, Kmns, K);
    
    temp1 = var(U_grp_size);
    U_variance_box(r) = temp1;
    fprintf('Variance = %f\n\n', temp1);

    fprintf('Diversity\n');

    [M3, M4] = M3_M4(U_grp_cell, K, d, A);
    
    temp1 = M4;
    U_diver_box(r) = temp1;
    fprintf('Diversity(M4) = %f\n\n', temp1);
    
    
    fprintf('Var of group var(M3)\n');

    temp1 = M3;
    U_var_of_grp_var_box(r) = temp1;

    fprintf('Var of group var(M3) = %f\n\n', temp1);

    fprintf('Var of group means(M2)\n');
    temp1 = M2_variance_of_grp_means(U_grp_cell, K, d, A);
    U_var_of_grp_mean_box(r) = temp1;
    fprintf('Var of group means(M2) = %f\n\n', temp1);  
    
end


%% -------------------------------- Random ------------------------------------

R_diver_box = zeros(reps, 1);
R_variance_box = zeros(reps, 1);
R_var_of_grp_var_box = zeros(reps, 1);
R_var_of_grp_mean_box = zeros(reps, 1);

for r=1:reps
    
    fprintf('\n\nRandom\n\n');
    R_grp_cell = cell(K, 1);
    R_grp_size = ones(K, 1);
    % temp = randperm(N);

    for i=1:N
        
        temp = randi(K);
        R_grp_cell{temp}(R_grp_size(temp)) = i;
        R_grp_size(temp) = R_grp_size(temp) + 1;
        
    end
    
    temp1 = var(R_grp_size);
    R_variance_box(r) = temp1;
    fprintf('Variance = %f\n\n', temp1);
    
    fprintf('Diversity\n');

    [M3, M4] = M3_M4(R_grp_cell, K, d, A);
    temp1 = M4;
    R_diver_box(r) = temp1;
    fprintf('Diversity Result(M4) = %f\n\n', temp1);
    
    fprintf('Var of group var(M3)\n');

    temp1 = M3;
    R_var_of_grp_var_box(r) = temp1;

    fprintf('Var of group var(M3) = %f\n\n', temp1);

    fprintf('Var of group means(M2)\n');
    temp1 = M2_variance_of_grp_means(R_grp_cell, K, d, A);
    R_var_of_grp_mean_box(r) = temp1;
    fprintf('Var of group means(M2) = %f\n\n', temp1); 
    
end

%% ---------------------------------K-means----------------------------------

KM_diver_box = zeros(reps, 1);
KM_variance_box = zeros(reps, 1);
KM_var_of_grp_var_box = zeros(reps, 1);
KM_var_of_grp_mean_box = zeros(reps, 1);

for r=1:reps
    
    fprintf('\n\nRandom\n\n');
    KM_grp_cell = cell(K, 1);
    KM_grp_size = ones(K, 1);
    % temp = randperm(N);

    idx = kmeans(A, K);
    idx = idx';
    
    for i=1:K
        KM_grp_cell{i} = find(idx==i);
        KM_grp_size(i) = length(KM_grp_cell{i});
    end
    
    
    temp1 = var(KM_grp_size);
    KM_variance_box(r) = temp1;
    fprintf('Variance = %f\n\n', temp1);
    
    fprintf('Diversity\n');

    [M3, M4] = M3_M4(KM_grp_cell, K, d, A);
    temp1 = M4;
    KM_diver_box(r) = temp1;
    fprintf('Diversity Result(M4) = %f\n\n', temp1);
    
    fprintf('Var of group var(M3)\n');

    temp1 = M3;
    KM_var_of_grp_var_box(r) = temp1;

    fprintf('Var of group var(M3) = %f\n\n', temp1);

    fprintf('Var of group means(M2)\n');
    temp1 = M2_variance_of_grp_means(KM_grp_cell, K, d, A);
    KM_var_of_grp_mean_box(r) = temp1;
    fprintf('Var of group means(M2) = %f\n\n', temp1); 
    
end

%% --------------------------------------------------------------------------



labl = ["DivGroup"; "Uniform k-means"; "Random"; "Kmeans"];

diversity  = [diver_box(:, final_lambda_ind), U_diver_box, R_diver_box, KM_diver_box];
vogv = [var_of_grp_var_box(:, final_lambda_ind), U_var_of_grp_var_box, R_var_of_grp_var_box, KM_var_of_grp_var_box];
% variance = [variance_box(:, final_lambda_ind), U_variance_box, R_variance_box];
vogm = [var_of_grp_mean_box(:, final_lambda_ind), U_var_of_grp_mean_box, R_var_of_grp_mean_box, KM_var_of_grp_mean_box];



% labl = ["DivGroup"; "Uniform k-means"; "Random"];
% 
% diversity  = [diver_box(:, final_lambda_ind), U_diver_box, R_diver_box];
% vogv = [var_of_grp_var_box(:, final_lambda_ind), U_var_of_grp_var_box, R_var_of_grp_var_box];
% % variance = [variance_box(:, final_lambda_ind), U_variance_box, R_variance_box];
% vogm = [var_of_grp_mean_box(:, final_lambda_ind), U_var_of_grp_mean_box, R_var_of_grp_mean_box];

kmeans_str = "TGD: ";
kmeans_str = strcat(kmeans_str, string(mean(KM_diver_box)));
kmeans_str = strcat(kmeans_str, "\n");
kmeans_str = strcat(kmeans_str, "VGV: ");
kmeans_str = strcat(kmeans_str, string(mean(KM_var_of_grp_var_box)));
kmeans_str = strcat(kmeans_str, "\n");
kmeans_str = strcat(kmeans_str, "VGM: ");
kmeans_str = strcat(kmeans_str, string(mean(KM_var_of_grp_mean_box)));

fid = fopen(strcat(dataset_name,'/',dirName, '/kmeans.txt'), 'wt');
fprintf(fid, kmeans_str);
fclose(fid);

% figure
% boxplot(variance, labl)
% hold on
% plot(mean(variance), '-ob', 'LineWidth', 2.3)
% % xlabel('\textbf{lambda}$(\lambda) \rightarrow$', 'Interpreter', 'latex', 'FontSize', 16)
% ylabel('\textbf{Variation of Group Size (VGS)} $\rightarrow$', 'Interpreter', 'latex', 'FontSize', 25)
% % set(gca,'FontSize',12, 'fontweight', 'bold')
% set(gca,'FontSize',10, 'fontweight', 'bold')
% print(strcat(dataset_name,'/',dirName, '/VGS_all_algos'), '-dpng');
% close



figure
boxplot(diversity, labl)
hold on
plot(mean(diversity), '-or', 'LineWidth', 2.3)
% title('Diversity')
% legend('Diversity')
% xlabel('\textbf{lambda}$(\lambda) \rightarrow$', 'Interpreter', 'latex', 'FontSize', 16)
ylabel('\textbf{Total Group Diversity (TGD)} $\rightarrow$', 'Interpreter', 'latex', 'FontSize', 18)
% set(gca,'FontSize',12, 'fontweight', 'bold')
set(gca,'FontSize',10, 'fontweight', 'bold')
print(strcat(dataset_name,'/',dirName, '/TGD_all_algos'), '-dpng');
close

figure
boxplot(vogm, labl)
hold on
plot(mean(vogm), '-ok', 'LineWidth', 2.3)
% title('Uniformity')
% xlabel('\textbf{lambda}$(\lambda) \rightarrow$', 'Interpreter', 'latex', 'FontSize', 16)
ylabel('\textbf{Variation of Group Means (VGM)} $\rightarrow$', 'Interpreter', 'latex', 'FontSize', 18)
% set(gca,'FontSize',12, 'fontweight', 'bold')
set(gca,'FontSize',10, 'fontweight', 'bold')
print(strcat(dataset_name,'/',dirName, '/VGM_all_algos'), '-dpng');
close


figure
boxplot(vogv, labl)
hold on
plot(mean(vogv), '-ok', 'LineWidth', 2.3)
% title('Uniformity')
% xlabel('\textbf{lambda}$(\lambda) \rightarrow$', 'Interpreter', 'latex', 'FontSize', 16)
ylabel('\textbf{Variation of Group Variance (VGV)} $\rightarrow$', 'Interpreter', 'latex', 'FontSize', 18)
% set(gca,'FontSize',12, 'fontweight', 'bold')
set(gca,'FontSize',10, 'fontweight', 'bold')
print(strcat(dataset_name,'/',dirName, '/VGV_all_algos'), '-dpng');
close


% figure
% for k=1:5
% 	temp3 = A(grp_cell{k}, :);
%     plot(temp3(:,1), temp3(:,2), '.-', 'Color', rand(1,3));
% 	hold on
% end
% 
% xlabel('$x_1~~ \rightarrow$', 'Interpreter', 'latex')
% ylabel('$x_2~~ \rightarrow$', 'Interpreter', 'latex')
% set(gca, 'FontSize', 12)
% print(strcat(dataset_name,'/',dirName, '/grp_distr'), '-dpng')
% close
